### PR TITLE
Remove dependency from @withgraphite/graphite-cli-routes

### LINKED ISSUE #18: Graphite routes are being deprecated
Hey there

We noticed that graphite is deprecating their `@withgraphite/graphite-cli-routes` package.

looking at the code, it seems `freephite` still uses it to get PR information when doing the sync (e.g. when running `fp repo sync`).

I think we can bypass that and use the GH api directly - this way we remove the Graphite API dep.

What do you think?

### PR DESCRIPTION
**Pull request by guilhermevrs**
**Context:**
The `@withgraphite/graphite-cli-routes` package has been deprecated, causing runtime issues for newly installed packages.

Newly installed package would break with the following error:

```
> fp
This package has been deprecated
UNCAUGHT EXCEPTION: Cannot read properties of undefined (reading 'pullRequestInfo')
UNCAUGHT EXCEPTION: TypeError: Cannot read properties of undefined (reading 'pullRequestInfo')
    at Object.<anonymous> ([REDACTED]/@bradymadden97/freephite-cli/lib/node_modules/@bradymadden97/freephite-cli/dist/src/lib/spiffy/pr_info_spf.js:32:58)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> ([REDACTED]/@bradymadden97/freephite-cli/lib/node_modules/@bradymadden97/freephite-cli/dist/src/background_tasks/fetch_pr_info.js:6:23)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
```

**Changes In This Pull Request:**
This PR removes any dependencies from `@withgraphite/graphite-cli-routes`.

Some types coming from it were replicated (to ease the dep removal).
And some methods (like the `downstack get` that never worked) were changed to make it work without errors.

I have also removed stuff like `survey` and `trace`,since we don't really care 🤷 

**Test Plan:**

- Build the cli files
- Run it locally

Commands to run:
- `fp`
- `fp downstack get`
- `fp stack submit`

Closes #18

### CODE REVIEW

**Comment by bradymadden97** [comment]
I think we need `getPrInfoForBranches` implemented for `fp rs` to work. Working on a patch now

**Comment by bradymadden97** [comment]
Also closes https://github.com/bradymadden97/freephite/issues/16

**Comment by bradymadden97** [comment]
Oh I think you disallowed me from pushing to your branch. I'll just merge this and push on top.

**Comment by guilhermevrs** [comment]
Thanks @bradymadden97 for including the fetch PR info!

**Pull request merged**
